export const DealershipData: Array<any> = [
  {
    id: 1,
    BankAccountName: 'bank account name',
    BankAccountNumber: '03-0131-0567783-000',
    BankBranchName: 'Riccarton',
    BankingCompany: 'ANZ',
    CellArea: '021',
    CellCountry: '+64',
    CellNumber: '335 5560',
    ContactName: 'Tim Hong',
    DateCreated: new Date(),
    DateModified: new Date(),
    Email: '123@123.com',
    FaxArea: '03',
    FaxCountry: '+64',
    FaxNumber: '335 6679',
    IsEnabled: true,
    Name: 'Jetski Imports Limited',
    PhoneArea: '03',
    PhoneCountry: '+64',
    PhoneNumber: '335 6677',
    Website: 'http://www.jetskiimportsltd.co.nz/',
    Addresses: [
      {
        Id: 2,
        AddressLine1: '228 Alec Craig Way',
        AddressLine2: '',
        AddressLine3: '',
        City: 'Whangaparaoa',
        ContactPhoneNumber: '',
        DateCreated: new Date(),
        DateModified: new Date(),
        IsDefault: true,
        Name: 'Head Quarter',
        OtherInformation: '',
        Postcode: '0930',
        Region: 'Gulf Harbour',
        Type: ''
      }
    ]
},
{
  id: 2,
  BankAccountName: 'bank account name',
  BankAccountNumber: '08-0131-0567783-000',
  BankBranchName: 'Bush Inn',
  BankingCompany: 'BNZ',
  CellArea: '021',
  CellCountry: '+64',
  CellNumber: '335 5560',
  ContactName: 'Marc Stevenson',
  DateCreated: new Date(),
  DateModified: new Date(),
  Email: '222@123.com',
  FaxArea: '03',
  FaxCountry: 'New Zealand',
  FaxNumber: '335 6679',
  IsEnabled: true,
  Name: 'JJ Motors',
  PhoneArea: '09',
  PhoneCountry: '+64',
  PhoneNumber: '2706522',
  Website: '',
  Addresses: [
    {
      Id: 1,
      AddressLine1: '3 Hans Street 1062 ',
      AddressLine2: '',
      AddressLine3: '',
      City: 'Auckland',
      ContactPhoneNumber: '',
      DateCreated: new Date(),
      DateModified: new Date(),
      IsDefault: true,
      Name: 'Head Quarter',
      OtherInformation: '',
      Postcode: '0930',
      Region: 'Otahuhu',
      Type: ''
    }
  ]
}];
