export const DealsData: Array<any> = [
  {
    Id: 1,
    AssignedToId: 'bank account name',
    CashManagerReference: '03-0131-0567783-000',
    Commission: 'Riccarton',
    CustomerId: '1',
    CustomerName: 'Thelma Campbell',
    DateCreated: '05.01.2016',
    DateModified: '12.01.2016',
    DealStatus: 'S',
    DealershipClawbackNotes: 'Sam 25%',
    DealershipCommission: '98.5',
    DocumentationFee: '150.00',
    FinanceCompanyId: '1',
    FinanceCompanyName: '?',
    FinanceVolume: '20,000',
    GuaranteedAssetProtection: '',
    MechanicalBreakDownInsurance: '',
    Number: 'D50001',
    OtherInsurance: '',
    OtherInsuranceNote: '',
    PaymentProtectionInsurance: '',
    Rate: '',
    SecurityDescription: '',
    SourceId: '',
    TermInMonths: ''
  },
  {
    Id: 2,
    AssignedToId: 'bank account name',
    CashManagerReference: '03-0131-0567783-000',
    Commission: 'Riccarton',
    CustomerId: '1',
    CustomerName: 'TSR Motors',
    DateCreated: '05.01.2016',
    DateModified: '12.01.2016',
    DealStatus: 'S',
    DealershipClawbackNotes: 'Sam 25%',
    DealershipCommission: '98.5',
    DocumentationFee: '150.00',
    FinanceCompanyId: '1',
    FinanceCompanyName: '?',
    FinanceVolume: '20,000',
    GuaranteedAssetProtection: '',
    MechanicalBreakDownInsurance: '',
    Number: 'D50002',
    OtherInsurance: '',
    OtherInsuranceNote: '',
    PaymentProtectionInsurance: '',
    Rate: '',
    SecurityDescription: '',
    SourceId: '',
    TermInMonths: ''
  }];
